name: Deploy to VM

on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 172.235.128.30 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh root@172.235.128.30 "
            cd /var/www/html/frontend-freeapp &&
            git reset --hard &&
            git pull origin main &&
            npm install &&
            npm run build
            systemctl restart caddy
          "
