name: Deploy to VM

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 172.235.128.30 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh root@172.235.128.30 "
            cd /var/www/freeapp/frontend-appfree &&
            git reset --hard &&
            git pull origin main &&
            npm install &&
            npm run build
          "
